/**
 * Proactive Goal Generation
 *
 * Examines cross-project patterns and architecture drift reports
 * to auto-generate maintenance/improvement goals. Goals are created
 * with 'candidate' status — requiring user approval before execution.
 */

import { v4 as uuidv4 } from 'uuid';
import { getDatabase } from '@/app/db/connection';
import { getGlobalPatterns, type CrossProjectPattern } from './crossProjectPatterns';
import { detectArchitectureDrift, type DriftItem, type DriftReport } from './architectureDrift';

// ============================================================================
// Types
// ============================================================================

export interface ProactiveGoalCandidate {
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high';
  source: 'pattern' | 'drift';
  triggerPatternId?: string;
  triggerDrift?: DriftItem;
  projectId: string;
  confidence: number;
}

export interface ProactiveGoalResult {
  goalId: string;
  title: string;
  projectId: string;
}

// ============================================================================
// Goal Generation
// ============================================================================

/**
 * Generate proactive goal candidates for a project based on
 * cross-project patterns and architecture drift.
 */
export function generateProactiveGoals(
  projectId: string,
  projectPath?: string
): ProactiveGoalCandidate[] {
  const candidates: ProactiveGoalCandidate[] = [];

  // 1. Goals from cross-project patterns
  const patterns = getGlobalPatterns({
    minConfidence: 0.6,
    status: 'active',
    limit: 20,
  });

  for (const pattern of patterns) {
    // Only generate goals for patterns relevant to this project
    if (!pattern.sourceProjectIds.includes(projectId)) continue;

    const candidate = patternToGoalCandidate(pattern, projectId);
    if (candidate) candidates.push(candidate);
  }

  // 2. Goals from architecture drift
  const driftReport = detectArchitectureDrift(projectId, projectPath);
  if (driftReport.overallHealth !== 'healthy') {
    const driftCandidates = driftToGoalCandidates(driftReport);
    candidates.push(...driftCandidates);
  }

  // Deduplicate by title similarity
  return deduplicateCandidates(candidates);
}

/**
 * Create a goal in the database from a candidate.
 * Returns the created goal ID.
 */
export function createGoalFromCandidate(candidate: ProactiveGoalCandidate): ProactiveGoalResult {
  const db = getDatabase();
  const goalId = uuidv4();
  const now = new Date().toISOString();

  // Build description with source context
  const fullDescription = [
    candidate.description,
    '',
    '---',
    `*Auto-generated by Vibeman proactive analysis (${candidate.source})*`,
    `*Confidence: ${Math.round(candidate.confidence * 100)}%*`,
    candidate.triggerPatternId ? `*Pattern: ${candidate.triggerPatternId}*` : '',
  ].filter(Boolean).join('\n');

  db.prepare(`
    INSERT INTO goals (id, project_id, title, description, status, created_at, updated_at)
    VALUES (?, ?, ?, ?, 'open', ?, ?)
  `).run(goalId, candidate.projectId, candidate.title, fullDescription, now, now);

  return {
    goalId,
    title: candidate.title,
    projectId: candidate.projectId,
  };
}

// ============================================================================
// Pattern -> Goal Conversion
// ============================================================================

function patternToGoalCandidate(
  pattern: CrossProjectPattern,
  projectId: string
): ProactiveGoalCandidate | null {
  // Only promote patterns with high confidence and multiple occurrences
  if (pattern.confidence < 0.6 || pattern.occurrenceCount < 2) return null;

  return {
    title: `Address recurring pattern: ${pattern.title}`,
    description: [
      `This pattern has been observed across ${pattern.occurrenceCount} projects:`,
      '',
      `**${pattern.title}**`,
      pattern.description,
      '',
      `Confidence: ${Math.round(pattern.confidence * 100)}%`,
      `Projects affected: ${pattern.sourceProjectIds.join(', ')}`,
    ].join('\n'),
    priority: pattern.confidence >= 0.8 ? 'high' : 'medium',
    source: 'pattern',
    triggerPatternId: pattern.id,
    projectId,
    confidence: pattern.confidence,
  };
}

// ============================================================================
// Drift -> Goal Conversion
// ============================================================================

function driftToGoalCandidates(report: DriftReport): ProactiveGoalCandidate[] {
  const candidates: ProactiveGoalCandidate[] = [];

  // Group drifts by context for consolidated goals
  const contextDrifts = new Map<string, DriftItem[]>();
  for (const drift of report.drifts) {
    const existing = contextDrifts.get(drift.contextId) || [];
    existing.push(drift);
    contextDrifts.set(drift.contextId, existing);
  }

  for (const [contextId, drifts] of contextDrifts) {
    const contextName = drifts[0].contextName;
    const hasOrphaned = drifts.some(d => d.type === 'orphaned_context');
    const missingFiles = drifts.filter(d => d.type === 'missing_file');
    const extraFiles = drifts.filter(d => d.type === 'extra_file');

    if (hasOrphaned) {
      candidates.push({
        title: `Clean up orphaned context: ${contextName}`,
        description: [
          `Context "${contextName}" (${contextId}) has no valid files on disk.`,
          'All declared file paths are missing.',
          '',
          'Options:',
          '- Remove the context if the feature was deleted',
          '- Update file paths if files were moved/renamed',
        ].join('\n'),
        priority: 'high',
        source: 'drift',
        triggerDrift: drifts[0],
        projectId: report.projectId,
        confidence: 0.9,
      });
    } else if (missingFiles.length > 0) {
      candidates.push({
        title: `Fix missing files in context: ${contextName}`,
        description: [
          `Context "${contextName}" has ${missingFiles.length} declared file(s) missing from disk:`,
          '',
          ...missingFiles.map(d => `- ${d.filePath}`),
          '',
          'These files may have been moved, renamed, or deleted.',
        ].join('\n'),
        priority: missingFiles.length > 3 ? 'high' : 'medium',
        source: 'drift',
        triggerDrift: missingFiles[0],
        projectId: report.projectId,
        confidence: 0.85,
      });
    }

    if (extraFiles.length >= 3) {
      candidates.push({
        title: `Register undeclared files in context: ${contextName}`,
        description: [
          `Context "${contextName}" has ${extraFiles.length} undeclared file(s) in its directories:`,
          '',
          ...extraFiles.slice(0, 10).map(d => `- ${d.filePath}`),
          extraFiles.length > 10 ? `- ... and ${extraFiles.length - 10} more` : '',
          '',
          'These files should be added to the context definition.',
        ].filter(Boolean).join('\n'),
        priority: 'low',
        source: 'drift',
        triggerDrift: extraFiles[0],
        projectId: report.projectId,
        confidence: 0.7,
      });
    }
  }

  return candidates;
}

// ============================================================================
// Deduplication
// ============================================================================

function deduplicateCandidates(candidates: ProactiveGoalCandidate[]): ProactiveGoalCandidate[] {
  const seen = new Set<string>();
  return candidates.filter(c => {
    // Normalize title for dedup
    const key = c.title.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
