/**
 * Knowledge Base File Exporter
 *
 * Exports KB entries to .claude/knowledge/ as LLM-optimized markdown files,
 * organized by domain. Each domain gets its own file with entries grouped
 * by pattern type. An _index.md provides a summary table.
 */

import { knowledgeRepository } from '@/app/db/repositories/knowledge.repository';
import { KNOWLEDGE_DOMAINS, KNOWLEDGE_DOMAIN_LABELS } from '@/app/db/models/knowledge.types';
import type { DbKnowledgeEntry, KnowledgeDomain } from '@/app/db/models/knowledge.types';
import fs from 'fs';
import path from 'path';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function safeParseJsonArray(json: string | null): string[] {
  if (!json) return [];
  try { return JSON.parse(json); } catch { return []; }
}

// ---------------------------------------------------------------------------
// Domain markdown generation
// ---------------------------------------------------------------------------

function exportDomainMarkdown(
  domain: KnowledgeDomain,
  entries: DbKnowledgeEntry[],
  timestamp: string
): string {
  const label = KNOWLEDGE_DOMAIN_LABELS[domain];
  const avgConfidence = Math.round(
    entries.reduce((sum, e) => sum + e.confidence, 0) / entries.length
  );

  const lines: string[] = [
    `# Knowledge Base: ${label}`,
    `<!-- Auto-generated by Vibeman KB. Last updated: ${timestamp} -->`,
    `<!-- Do not edit manually -- changes will be overwritten -->`,
    '',
    `> ${entries.length} patterns | Avg confidence: ${avgConfidence}%`,
    '',
  ];

  // Group by pattern_type
  const sections: [string, DbKnowledgeEntry[]][] = [
    ['Best Practices', entries.filter(e => e.pattern_type === 'best_practice')],
    ['Conventions', entries.filter(e => e.pattern_type === 'convention')],
    ['Anti-Patterns', entries.filter(e => e.pattern_type === 'anti_pattern')],
    ['Gotchas', entries.filter(e => e.pattern_type === 'gotcha')],
    ['Optimizations', entries.filter(e => e.pattern_type === 'optimization')],
  ];

  for (const [sectionTitle, sectionEntries] of sections) {
    if (sectionEntries.length === 0) continue;
    lines.push(`## ${sectionTitle}`, '');

    for (const entry of sectionEntries) {
      lines.push(`### ${entry.title}`);
      lines.push(
        `**Confidence**: ${entry.confidence}%`
        + ` | **Applied**: ${entry.times_applied} times`
        + (entry.times_helpful > 0
          ? ` | **Helpful**: ${entry.times_helpful}/${entry.times_applied}`
          : '')
      );
      lines.push(entry.pattern);

      if (entry.rationale) {
        lines.push('', `**Rationale**: ${entry.rationale}`);
      }

      if (entry.anti_pattern) {
        lines.push('', `**Avoid**: ${entry.anti_pattern}`);
      }

      if (entry.code_example) {
        lines.push('', '```', entry.code_example, '```');
      }

      const tags = safeParseJsonArray(entry.tags);
      if (tags.length > 0) {
        lines.push('', `**Tags**: ${tags.join(', ')}`);
      }

      lines.push('', '---', '');
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Index markdown generation
// ---------------------------------------------------------------------------

function exportIndexMarkdown(
  byDomain: Map<KnowledgeDomain, DbKnowledgeEntry[]>,
  timestamp: string,
  totalEntries: number
): string {
  const lines: string[] = [
    '# Vibeman Knowledge Base',
    `<!-- Auto-generated. Last updated: ${timestamp} -->`,
    '',
    `> ${totalEntries} entries across ${byDomain.size} domains`,
    '',
    '| Domain | Entries | Avg Confidence | Top Pattern |',
    '|--------|---------|----------------|-------------|',
  ];

  for (const domain of KNOWLEDGE_DOMAINS) {
    const entries = byDomain.get(domain) || [];
    if (entries.length === 0) continue;
    const avgConf = Math.round(
      entries.reduce((s, e) => s + e.confidence, 0) / entries.length
    );
    // Entries are already sorted by confidence DESC from the repository
    const topEntry = entries[0];
    lines.push(
      `| ${KNOWLEDGE_DOMAIN_LABELS[domain]} | ${entries.length} | ${avgConf}% | ${topEntry.title} |`
    );
  }

  lines.push('', '## Usage', '');
  lines.push('- Query specific domains: read `.claude/knowledge/{domain}.md`');
  lines.push('- In-session queries: use `get_knowledge` MCP tool');
  lines.push('- Report outcomes: POST `/api/knowledge-base` with `action=feedback`');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Export all active KB entries to .claude/knowledge/ directory.
 * Creates one markdown file per domain plus an _index.md summary.
 * Removes stale domain files when a domain has no active entries.
 */
export function exportToFiles(
  projectPath: string
): { domainsWritten: number; entriesWritten: number } {
  const knowledgeDir = path.join(projectPath, '.claude', 'knowledge');

  // Ensure directory exists
  fs.mkdirSync(knowledgeDir, { recursive: true });

  const allEntries = knowledgeRepository.getActiveForExport();

  // Group by domain
  const byDomain = new Map<KnowledgeDomain, DbKnowledgeEntry[]>();
  for (const entry of allEntries) {
    const domain = entry.domain as KnowledgeDomain;
    if (!byDomain.has(domain)) byDomain.set(domain, []);
    byDomain.get(domain)!.push(entry);
  }

  let domainsWritten = 0;
  let entriesWritten = 0;
  const now = new Date().toISOString();

  // Write domain files
  for (const domain of KNOWLEDGE_DOMAINS) {
    const entries = byDomain.get(domain) || [];
    const filePath = path.join(knowledgeDir, `${domain}.md`);

    if (entries.length === 0) {
      // Remove stale domain file if it exists
      if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
      continue;
    }

    const content = exportDomainMarkdown(domain, entries, now);
    fs.writeFileSync(filePath, content, 'utf-8');
    domainsWritten++;
    entriesWritten += entries.length;
  }

  // Write index file
  const indexContent = exportIndexMarkdown(byDomain, now, entriesWritten);
  fs.writeFileSync(path.join(knowledgeDir, '_index.md'), indexContent, 'utf-8');

  return { domainsWritten, entriesWritten };
}
