/**
 * Unused Code Cleanup Prompt Template
 * Instructs Claude Code to verify and safely remove unused code files
 *
 * Migrated from:
 * src/app/features/Onboarding/sub_Blueprint/lib/prompts/unusedCleanup.ts
 */

export interface UnusedFile {
  filePath: string;
  relativePath: string;
  exports: string[];
  reason: string;
}

export interface CleanupPromptParams {
  unusedFiles: UnusedFile[];
  stats?: {
    totalFiles: number;
    totalExports: number;
    unusedExports: number;
  };
}

export function buildCleanupPrompt(params: CleanupPromptParams): string {
  const { unusedFiles, stats } = params;

  const fileList = unusedFiles.map((file, index) =>
    `${index + 1}. \`${file.relativePath}\`
   - Exports: ${file.exports.join(', ')}
   - Reason: ${file.reason}`
  ).join('\n\n');

  return `# Unused Code Cleanup

## Objective
Verify and remove unused code files detected by static analysis.

## Files to Review (${unusedFiles.length} total)

${fileList}

## Task Instructions

### 1. Verification Phase
For each file listed above, perform thorough analysis:

**Static Analysis Checks:**
- Search for dynamic imports (e.g., \`import()\`, \`require()\`)
- Check for string-based references (e.g., \`componentMap['${unusedFiles[0]?.exports[0] || 'ComponentName'}']\`)
- Look for configuration-based usage (e.g., route configs, plugin registries)
- Verify no test files depend on these components
- Search for references in:
  - Comment blocks (might indicate future usage)
  - Storybook files
  - Documentation files
  - Configuration files (webpack, vite, etc.)

**Framework-Specific Checks (Next.js):**
- Verify not used by Next.js router (app directory convention)
- Check for Server Actions or API route handlers
- Look for middleware or layout dependencies
- Confirm not referenced in \`next.config.js\` or similar configs

**Edge Cases:**
- Check if files are re-exported from barrel files (index.ts)
- Look for usage in monorepo packages or workspaces
- Verify not used in build scripts or generators
- Check for dynamic component loading patterns

### 2. Cleanup Phase
Only delete files that are confirmed unused after verification:

1. **Before Deletion:**
   - Create a git branch for this cleanup: \`git checkout -b cleanup/unused-components-YYYY-MM-DD\`
   - Create a backup manifest in \`docs/cleanup/unused-files-backup-YYYY-MM-DD.json\`

2. **Deletion Process:**
   - Delete confirmed unused files
   - Update any related barrel exports (index.ts files)
   - Remove corresponding test files if they exist
   - Clean up any unused imports in other files that referenced the deleted files

3. **Post-Deletion:**
   - Run the build: \`npm run build\`
   - Run tests: \`npm test\` (if available)
   - Verify the application still functions correctly

### 3. Report Generation
Create a markdown report in \`docs/cleanup/cleanup-report-YYYY-MM-DD.md\` containing:

**Report Structure:**
\`\`\`markdown
# Unused Code Cleanup Report
**Date:** YYYY-MM-DD
**Branch:** cleanup/unused-components-YYYY-MM-DD

## Summary
- Total files analyzed: X
- Files deleted: Y
- Files kept (with justification): Z
- Lines of code removed: ~N

## Deleted Files
[List each deleted file with path and reason]

## Files Kept (Not Deleted)
[List each file that was flagged but kept, with detailed justification]

## Verification Results
- Build status: Success/Failure
- Tests status: Pass/Fail
- Application functionality: Verified/Issues Found

## Next Steps
[Any follow-up actions needed]
\`\`\`

${stats ? `
## Statistics

- Total files analyzed: ${stats.totalFiles}
- Total exports: ${stats.totalExports}
- Unused exports: ${stats.unusedExports}
` : ''}

## Safety Guidelines

**CRITICAL RULES:**
- **DO NOT** delete files that have ANY uncertainty
- **DO** create a git commit with all deletions for easy rollback
- **DO** run the build and tests after cleanup
- **DO** verify the application still functions correctly
- **DO** preserve files if they're part of public API or exported by the library

**Best Practices:**
- Make incremental commits (group related deletions)
- Test after each batch of deletions
- Document your reasoning for keeping files
- Be conservative - it's better to keep an unused file than break the app

## Expected Output

At the end of this task:
1. A cleanup report in \`docs/cleanup/\`
2. A backup manifest with file contents before deletion
3. Clean git commits with descriptive messages
4. Build and tests passing
5. Application verified to work correctly

Generated by Blueprint Unused Code Scan
`;
}
