/**
 * API Route: Scan Profiles
 *
 * GET    /api/scan-profiles?projectId=...         - List profiles for a project
 * GET    /api/scan-profiles?goalId=...            - List profiles for a goal
 * POST   /api/scan-profiles                       - Create a profile (or auto-generate from goal)
 * PATCH  /api/scan-profiles                       - Update a profile
 * DELETE /api/scan-profiles?id=...                - Delete a profile
 */

import { NextRequest, NextResponse } from 'next/server';
import { scanProfileRepository } from '@/app/db/repositories/scan-profile.repository';
import { goalRepository } from '@/app/db/repositories/goal.repository';
import { buildScanConfigFromGoal } from '@/lib/ideas/goalScanEngine';
import { logger } from '@/lib/logger';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('projectId');
    const goalId = searchParams.get('goalId');

    let profiles;
    if (goalId) {
      profiles = scanProfileRepository.getByGoal(goalId);
    } else {
      profiles = scanProfileRepository.getByProject(projectId || 'default');
    }

    return NextResponse.json({
      success: true,
      data: profiles,
      count: profiles.length,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to get scan profiles';
    logger.error('[ScanProfiles] GET error:', error);
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { projectId, goalId, name, description, scanTypes, contextIds, groupIds, promptOverrides, autoGenerate } = body;

    if (!projectId) {
      return NextResponse.json(
        { success: false, error: 'projectId is required' },
        { status: 400 },
      );
    }

    // Auto-generate profile from goal metadata
    if (autoGenerate && goalId) {
      const goal = goalRepository.getGoalById(goalId);
      if (!goal) {
        return NextResponse.json(
          { success: false, error: 'Goal not found' },
          { status: 404 },
        );
      }

      const config = buildScanConfigFromGoal({
        title: goal.title,
        description: goal.description,
        contextId: goal.context_id,
      });

      const profile = scanProfileRepository.create({
        projectId,
        goalId,
        name: name || `Scan: ${goal.title}`,
        description: config.reasoning,
        scanTypes: config.scanTypes,
        contextIds: config.contextIds,
        groupIds: config.groupIds,
        promptOverrides,
      });

      return NextResponse.json({
        success: true,
        data: profile,
        autoGenerated: true,
        reasoning: config.reasoning,
      });
    }

    // Manual profile creation
    if (!name || !scanTypes || scanTypes.length === 0) {
      return NextResponse.json(
        { success: false, error: 'name and scanTypes are required' },
        { status: 400 },
      );
    }

    const profile = scanProfileRepository.create({
      projectId,
      goalId,
      name,
      description,
      scanTypes,
      contextIds,
      groupIds,
      promptOverrides,
    });

    return NextResponse.json({ success: true, data: profile });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to create scan profile';
    logger.error('[ScanProfiles] POST error:', error);
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, recordRun, ...updates } = body;

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'id is required' },
        { status: 400 },
      );
    }

    // Record a scan run (increment counter + update timestamp)
    if (recordRun) {
      scanProfileRepository.recordRun(id);
      return NextResponse.json({ success: true, message: 'Run recorded' });
    }

    const profile = scanProfileRepository.update(id, updates);
    if (!profile) {
      return NextResponse.json(
        { success: false, error: 'Profile not found' },
        { status: 404 },
      );
    }

    return NextResponse.json({ success: true, data: profile });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to update scan profile';
    logger.error('[ScanProfiles] PATCH error:', error);
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'id is required' },
        { status: 400 },
      );
    }

    const deleted = scanProfileRepository.delete(id);
    if (!deleted) {
      return NextResponse.json(
        { success: false, error: 'Profile not found' },
        { status: 404 },
      );
    }

    return NextResponse.json({ success: true, message: 'Profile deleted' });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to delete scan profile';
    logger.error('[ScanProfiles] DELETE error:', error);
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
