/**
 * Migration 201: Conductor Specs Table
 *
 * Creates the conductor_specs table for persisting spec metadata
 * generated by the spec writer stage. Each spec links to a conductor run
 * and tracks a backlog item through the spec generation pipeline.
 */

import type { DbConnection } from '../drivers/types';
import type { MigrationLogger } from './migration.utils';

export function migrate201ConductorSpecs(db: DbConnection, logger?: MigrationLogger): void {
  db.exec(`
    CREATE TABLE IF NOT EXISTS conductor_specs (
      id TEXT PRIMARY KEY,
      run_id TEXT NOT NULL,
      backlog_item_id TEXT NOT NULL,
      sequence_number INTEGER NOT NULL,
      title TEXT NOT NULL,
      slug TEXT NOT NULL,
      affected_files TEXT NOT NULL,
      complexity TEXT NOT NULL CHECK (complexity IN ('S', 'M', 'L')),
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executing', 'completed', 'failed')),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (run_id) REFERENCES conductor_runs(id)
    );

    CREATE INDEX IF NOT EXISTS idx_conductor_specs_run ON conductor_specs(run_id, sequence_number);
  `);

  logger?.success('Migration 201: conductor_specs table created');
}
