import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackgroundPattern from "../components/BackgroundPattern";
import QueryProvider from "../components/QueryProvider";
import { ModalProvider } from "../contexts/ModalContext";
import ContextOverview from "./coder/Context/ContextOverview/ContextOverview";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundPattern />
        <QueryProvider>
          <ModalProvider>
            {children}
            <ContextOverview />
          </ModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
