/**
 * Accept Goal Candidates API
 * Creates goals from accepted LLM-generated candidates
 */

import { NextRequest, NextResponse } from 'next/server';
import { logger } from '@/lib/logger';
import { goalDb } from '@/app/db';
import { projectDb } from '@/lib/project_database';
import { randomUUID } from 'crypto';
import { fireAndForgetGoalAnalysis } from '@/lib/goals';

interface GoalCandidate {
  title: string;
  description: string;
  reasoning: string;
  priorityScore: number;
  suggestedContext?: string;
  category: string;
}

interface AcceptRequest {
  projectId: string;
  candidates: GoalCandidate[];
  createAnalysis?: boolean;
}

/**
 * POST /api/standup/automation/accept-candidates
 * Accept and create goals from candidates
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as AcceptRequest;
    const { projectId, candidates, createAnalysis = true } = body;

    if (!projectId || !candidates || !Array.isArray(candidates)) {
      return NextResponse.json(
        { success: false, error: 'projectId and candidates array required' },
        { status: 400 }
      );
    }

    logger.info('[Accept Candidates API] Accepting candidates', {
      projectId,
      candidateCount: candidates.length,
      createAnalysis,
    });

    const project = projectDb.getProject(projectId);
    if (!project) {
      return NextResponse.json(
        { success: false, error: 'Project not found' },
        { status: 404 }
      );
    }

    const createdGoals: Array<{ id: string; title: string }> = [];
    const errors: string[] = [];

    // Get max order index for the project
    let orderIndex = goalDb.getMaxOrderIndex(projectId) + 1;

    for (const candidate of candidates) {
      try {
        const goalId = randomUUID();

        const goal = goalDb.createGoal({
          id: goalId,
          project_id: projectId,
          context_id: undefined, // Can be assigned later
          title: candidate.title,
          description: `${candidate.description}\n\n---\n*Generated by automation (${candidate.category}, score: ${candidate.priorityScore})*\n*Reasoning: ${candidate.reasoning}*`,
          status: 'open',
          order_index: orderIndex++,
        });

        createdGoals.push({ id: goal.id, title: goal.title });

        // Fire-and-forget goal analysis (creates Claude Code requirement)
        if (createAnalysis && project.path) {
          fireAndForgetGoalAnalysis(
            {
              goal,
              projectPath: project.path,
            },
            `Auto-create analysis for accepted candidate: ${goal.id}`
          );
        }

        logger.info('[Accept Candidates API] Goal created', {
          goalId: goal.id,
          title: goal.title,
        });
      } catch (error) {
        const msg = error instanceof Error ? error.message : 'Unknown error';
        errors.push(`Failed to create "${candidate.title}": ${msg}`);
        logger.error('[Accept Candidates API] Failed to create goal', {
          title: candidate.title,
          error: msg,
        });
      }
    }

    return NextResponse.json({
      success: true,
      created: createdGoals,
      errors,
      summary: {
        requested: candidates.length,
        created: createdGoals.length,
        failed: errors.length,
      },
    });
  } catch (error) {
    logger.error('[Accept Candidates API] Error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to accept candidates',
      },
      { status: 500 }
    );
  }
}
