'use client';

import { useRefactorStore } from '@/stores/refactorStore';
import { useActiveProjectStore } from '@/stores/activeProjectStore';
import { FileText, CheckCircle, Package, Sparkles } from 'lucide-react';
import { useState } from 'react';
import {
  WizardStepContainer,
  WizardHeader,
  CyberCard,
  ProgressBar,
  StatCard,
  WizardActions,
} from '@/components/ui/wizard';
import { motion } from 'framer-motion';

const BATCH_SIZE = 20;

export default function ExecuteStep() {
  const { opportunities, selectedOpportunities, setCurrentStep } = useRefactorStore();
  const activeProject = useActiveProjectStore(state => state.activeProject);
  const [isCreating, setIsCreating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [createdFiles, setCreatedFiles] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);

  const selectedOpps = opportunities.filter(o => selectedOpportunities.has(o.id));
  const batchCount = Math.ceil(selectedOpps.length / BATCH_SIZE);

  const createRequirementFiles = async () => {
    if (!activeProject?.path) {
      setError('No active project selected');
      return;
    }

    setIsCreating(true);
    setProgress(0);
    setError(null);
    const created: string[] = [];

    try {
      // Split opportunities into batches
      const batches = [];
      for (let i = 0; i < selectedOpps.length; i += BATCH_SIZE) {
        batches.push(selectedOpps.slice(i, i + BATCH_SIZE));
      }

      // Create a requirement file for each batch
      for (let batchIndex = 0; batchIndex < batches.length; batchIndex++) {
        const batch = batches[batchIndex];
        const batchNum = batchIndex + 1;

        // Generate requirement content
        const content = generateRequirementContent(batch, batchNum, batches.length);

        // Create the requirement file
        const response = await fetch('/api/claude-code/requirement', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            projectPath: activeProject.path,
            requirementName: `refactor-batch-${batchNum}`,
            content,
            overwrite: true,
          }),
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error || `Failed to create requirement file ${batchNum}`);
        }

        const data = await response.json();
        created.push(data.fileName || `refactor-batch-${batchNum}.md`);

        // Update progress
        setProgress(((batchIndex + 1) / batches.length) * 100);
      }

      setCreatedFiles(created);
      setProgress(100);
    } catch (err) {
      console.error('Error creating requirement files:', err);
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setIsCreating(false);
    }
  };

  const generateRequirementContent = (
    batch: typeof selectedOpps,
    batchNum: number,
    totalBatches: number
  ): string => {
    const projectName = activeProject?.name || 'Project';

    let content = `# Refactoring Tasks - Batch ${batchNum} of ${totalBatches}

> **⚠️ AUTOMATED REFACTORING BATCH**
> This requirement was generated by the Vibeman Refactor Wizard as part of an automated code improvement process.

## Context

Project: **${projectName}**
Total issues in this batch: **${batch.length}**

## Instructions

This batch contains ${batch.length} refactoring opportunities identified through automated analysis. Please review each issue and implement the suggested fixes.

**Important guidelines:**
- Review each change carefully before implementing
- Run tests after each logical group of changes
- Commit changes incrementally with descriptive messages
- If an issue is not applicable or incorrect, document why and skip it

---

## Issues to Address

`;

    // Add each opportunity with details
    batch.forEach((opp, index) => {
      content += `### ${index + 1}. ${opp.title}

**Category:** ${opp.category}
**Severity:** ${opp.severity}
**Effort:** ${opp.effort}
${opp.estimatedTime ? `**Estimated Time:** ${opp.estimatedTime}` : ''}

**Description:**
${opp.description}

**Impact:**
${opp.impact}

**Files Affected:**
${opp.files.map(f => `- \`${f}\``).join('\n')}

${opp.lineNumbers ? `**Line Numbers:**
${Object.entries(opp.lineNumbers).map(([file, lines]) => `- ${file}: lines ${lines.join(', ')}`).join('\n')}` : ''}

${opp.suggestedFix ? `**Suggested Fix:**
\`\`\`
${opp.suggestedFix}
\`\`\`
` : ''}

${opp.autoFixAvailable ? '✅ **Auto-fix available** - This issue can be automatically resolved.' : ''}

---

`;
    });

    content += `
## Completion Checklist

- [ ] All ${batch.length} issues reviewed
- [ ] Applicable fixes implemented
- [ ] Tests passing
- [ ] Code committed with descriptive messages
- [ ] Any skipped issues documented with reasoning

## Notes

Add any notes, observations, or blockers encountered during implementation here.
`;

    return content;
  };

  const isCompleted = createdFiles.length > 0 && !isCreating;

  return (
    <WizardStepContainer>
      {/* Header */}
      <WizardHeader
        title="Create Requirement Files"
        description="Generate Claude Code requirements for automated refactoring"
      />

      {/* Batch Info */}
      <CyberCard>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="text-white font-medium mb-1">Refactoring Strategy</h4>
              <p className="text-gray-400 text-sm">
                Issues will be bundled into manageable batches for systematic resolution
              </p>
            </div>
            <div className="p-3 bg-gradient-to-br from-cyan-500/10 to-blue-500/10 rounded-lg border border-cyan-500/30">
              <Sparkles className="w-6 h-6 text-cyan-400" />
            </div>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-3 gap-3">
            <StatCard
              label="Total Issues"
              value={selectedOpps.length}
              icon={FileText}
              variant="info"
            />
            <StatCard
              label="Batch Size"
              value={BATCH_SIZE}
              icon={Package}
              variant="info"
            />
            <StatCard
              label="Requirement Files"
              value={batchCount}
              icon={FileText}
              variant={isCompleted ? 'success' : 'info'}
            />
          </div>
        </div>
      </CyberCard>

      {/* Batch Breakdown */}
      <CyberCard variant="dark">
        <h4 className="text-white font-medium mb-3 flex items-center gap-2">
          <Package className="w-4 h-4 text-cyan-400" />
          Batch Breakdown
        </h4>
        <div className="space-y-2 max-h-48 overflow-y-auto pr-2">
          {Array.from({ length: batchCount }).map((_, index) => {
            const batchNum = index + 1;
            const startIdx = index * BATCH_SIZE;
            const endIdx = Math.min(startIdx + BATCH_SIZE, selectedOpps.length);
            const batchSize = endIdx - startIdx;
            const isCreated = createdFiles.length > index;

            return (
              <motion.div
                key={batchNum}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.05 }}
                className={`p-3 rounded-lg border transition-all ${
                  isCreated
                    ? 'bg-green-500/10 border-green-500/30'
                    : 'bg-gray-800/40 border-gray-700/50'
                }`}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-sm font-mono ${
                      isCreated
                        ? 'bg-green-500/20 text-green-300 border border-green-500/30'
                        : 'bg-cyan-500/10 text-cyan-400 border border-cyan-500/20'
                    }`}>
                      {batchNum}
                    </div>
                    <div>
                      <p className="text-white text-sm font-medium">
                        Batch {batchNum}
                      </p>
                      <p className="text-gray-400 text-xs">
                        {batchSize} issue{batchSize !== 1 ? 's' : ''} • Issues {startIdx + 1}-{endIdx}
                      </p>
                    </div>
                  </div>
                  {isCreated && (
                    <CheckCircle className="w-5 h-5 text-green-400" />
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>
      </CyberCard>

      {/* Progress */}
      {isCreating && (
        <ProgressBar
          progress={progress}
          label={`Creating requirement files... (${createdFiles.length}/${batchCount})`}
          variant="cyan"
        />
      )}

      {/* Error */}
      {error && (
        <CyberCard variant="dark" className="bg-red-500/10 border-red-500/30">
          <div className="flex items-start gap-2">
            <div className="text-red-400 text-sm">
              <p className="font-medium mb-1">Error creating requirement files</p>
              <p className="text-red-300/80">{error}</p>
            </div>
          </div>
        </CyberCard>
      )}

      {/* Success Message */}
      {isCompleted && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-gradient-to-r from-green-500/10 to-cyan-500/10 border border-green-500/30 rounded-lg p-4"
        >
          <div className="flex items-start gap-3">
            <CheckCircle className="w-6 h-6 text-green-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <h4 className="text-green-300 font-medium mb-2">
                Requirement Files Created Successfully!
              </h4>
              <p className="text-gray-300 text-sm mb-3">
                {createdFiles.length} requirement file{createdFiles.length !== 1 ? 's have' : ' has'} been created in <code className="px-1.5 py-0.5 bg-black/30 rounded text-xs font-mono">.claude/commands/</code>
              </p>
              <div className="space-y-1">
                {createdFiles.map((file, index) => (
                  <div key={index} className="text-xs text-gray-400 font-mono">
                    ✓ {file}
                  </div>
                ))}
              </div>
              <p className="text-gray-400 text-sm mt-3">
                Use Claude Code to execute these requirements and implement the refactoring changes.
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Actions */}
      <WizardActions
        onBack={isCreating ? undefined : () => setCurrentStep('review')}
        backDisabled={isCreating}
        onNext={isCompleted ? () => setCurrentStep('results') : createRequirementFiles}
        nextLabel={isCompleted ? 'View Summary' : 'Create Requirement Files'}
        nextIcon={isCompleted ? CheckCircle : FileText}
        nextDisabled={isCreating}
        nextLoading={isCreating}
        nextVariant={isCompleted ? 'success' : 'primary'}
      />
    </WizardStepContainer>
  );
}
