'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileCode, Copy, Check, Download } from 'lucide-react';
import type { EvaluatedFeedback } from '../lib/types';

interface ClaudeRequirementModalProps {
  isOpen: boolean;
  onClose: () => void;
  feedback: EvaluatedFeedback | null;
}

export default function ClaudeRequirementModal({
  isOpen,
  onClose,
  feedback,
}: ClaudeRequirementModalProps) {
  const [copied, setCopied] = useState(false);

  if (!feedback) return null;

  // Generate mock Claude Code requirement content
  const requirementContent = `# Bug Fix: ${feedback.summary}

## Context
**Source:** ${feedback.channel.charAt(0).toUpperCase() + feedback.channel.slice(1)} feedback
**Reporter:** ${feedback.author}
**Priority:** ${feedback.priority.toUpperCase()}
**Ticket:** ${feedback.ticket?.key || 'N/A'}

## Problem Description
${feedback.content}

## Suggested Solution
${feedback.suggestedAction}

## Technical Details
- **Category:** ${feedback.category}
- **Evaluation Date:** ${feedback.evaluatedAt.toLocaleDateString()}
- **Impact:** ${feedback.priority === 'critical' ? 'High - Immediate attention required' : feedback.priority === 'high' ? 'Medium-High - Should be addressed soon' : 'Low-Medium - Can be scheduled'}

## Implementation Steps
1. Reproduce the issue in development environment
2. Identify root cause in the codebase
3. Implement fix with proper error handling
4. Add unit tests to prevent regression
5. Test fix in staging environment
6. Deploy to production with monitoring

## Acceptance Criteria
- [ ] Bug is no longer reproducible
- [ ] Tests pass successfully
- [ ] No new issues introduced
- [ ] Code review approved
- [ ] Documentation updated if needed

## Files to Check
- Check settings initialization code
- Review user preference persistence logic
- Verify localStorage/session handling
- Check app lifecycle hooks

## Additional Notes
Generated automatically from social media feedback. Please verify all assumptions before implementing.

---
Generated by Vibeman AI on ${new Date().toLocaleString()}
`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(requirementContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([requirementContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `requirement-${feedback.ticket?.key || 'bug'}-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
          />

          {/* Modal */}
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-4xl max-h-[90vh] overflow-hidden rounded-2xl bg-gray-900 border border-gray-700/50 shadow-2xl"
            >
              {/* Header */}
              <div className="sticky top-0 z-10 flex items-center justify-between px-6 py-4 border-b border-gray-700/50 bg-gray-900/95 backdrop-blur-sm">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-blue-500/20">
                    <FileCode className="w-5 h-5 text-blue-400" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-white">Claude Code Requirement</h2>
                    <p className="text-sm text-gray-400">
                      {feedback.ticket?.key || 'Bug Fix'} - Auto-generated
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-2 px-3 py-2 rounded-lg bg-gray-800 hover:bg-gray-700 text-white transition-colors"
                  >
                    {copied ? (
                      <>
                        <Check className="w-4 h-4 text-emerald-400" />
                        <span className="text-emerald-400">Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-3 py-2 rounded-lg bg-gray-800 hover:bg-gray-700 text-white transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download</span>
                  </button>
                  <button
                    onClick={onClose}
                    className="p-2 rounded-lg text-gray-400 hover:text-white hover:bg-gray-800 transition-colors"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>

              {/* Content */}
              <div className="overflow-y-auto max-h-[calc(90vh-80px)] p-6">
                <div className="relative">
                  {/* Code block */}
                  <pre className="p-6 rounded-lg bg-black/40 border border-gray-800/50 overflow-x-auto">
                    <code className="text-sm text-gray-300 font-mono leading-relaxed whitespace-pre-wrap">
                      {requirementContent}
                    </code>
                  </pre>

                  {/* Watermark */}
                  <div className="mt-4 p-4 rounded-lg bg-blue-500/10 border border-blue-500/20">
                    <p className="text-sm text-blue-300">
                      <strong>Note:</strong> This requirement was automatically generated from social
                      media feedback. Review and adjust as needed before implementation.
                    </p>
                  </div>
                </div>
              </div>

              {/* Footer */}
              <div className="sticky bottom-0 flex justify-between items-center px-6 py-4 border-t border-gray-700/50 bg-gray-900/95 backdrop-blur-sm">
                <p className="text-sm text-gray-400">
                  Ready to use with Claude Code CLI
                </p>
                <button
                  onClick={onClose}
                  className="px-4 py-2 rounded-lg bg-gray-800 hover:bg-gray-700 text-white transition-colors"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </div>
        </>
      )}
    </AnimatePresence>
  );
}
