/**
 * Brain 2.0 Type Definitions
 * Types for behavioral learning and autonomous reflection system
 */

// Signal types for behavioral tracking
export type BehavioralSignalType =
  | 'git_activity'
  | 'api_focus'
  | 'context_focus'
  | 'implementation'
  | 'cross_task_analysis'
  | 'cross_task_selection'
  | 'cli_memory';

// Reflection trigger types
export type ReflectionTriggerType = 'threshold' | 'scheduled' | 'manual';

// Reflection status
export type ReflectionStatus = 'pending' | 'running' | 'completed' | 'failed';

// Reflection scope
export type ReflectionScope = 'project' | 'global';

/**
 * Behavioral Signal - tracks user activity patterns
 */
export interface DbBehavioralSignal {
  id: string;
  project_id: string;
  signal_type: BehavioralSignalType;
  context_id: string | null;
  context_name: string | null;
  data: string; // JSON payload
  weight: number;
  timestamp: string;
  created_at: string;
  decay_applied_at: string | null;
}

/**
 * Signal data payloads by type
 */
export interface GitActivitySignalData {
  filesChanged: string[];
  commitMessage: string;
  linesAdded: number;
  linesRemoved: number;
  branch: string;
  commitSha?: string;
}

export interface ApiFocusSignalData {
  endpoint: string;
  method: string;
  callCount: number;
  avgResponseTime: number;
  errorRate: number;
}

export interface ContextFocusSignalData {
  contextId: string;
  contextName: string;
  duration: number; // ms spent
  actions: string[]; // 'view', 'edit_files', 'run_scan', etc.
}

export interface ImplementationSignalData {
  requirementId: string;
  requirementName: string;
  directionId?: string;
  contextId: string | null;
  filesCreated: string[];
  filesModified: string[];
  filesDeleted: string[];
  success: boolean;
  executionTimeMs: number;
  error?: string;
}

export interface CrossTaskAnalysisSignalData {
  planId: string;
  workspaceId: string | null;
  projectIds: string[];
  requirement: string;
  requirementSummary: string;
  plansGenerated: number;
  success: boolean;
  executionTimeMs: number;
}

export interface CrossTaskSelectionSignalData {
  planId: string;
  selectedPlan: 1 | 2 | 3;
  planTitle: string;
  userNotes: string | null;
  projectIds: string[];
}

export interface CliMemorySignalData {
  category: 'decision' | 'insight' | 'pattern' | 'context' | 'lesson';
  message: string;
  source: 'claude_code_cli';
  sessionContext?: string;  // optional: what user was working on
  files?: string[];         // optional: related files
}

/**
 * Direction Outcome - tracks implementation results
 */
export interface DbDirectionOutcome {
  id: string;
  direction_id: string;
  project_id: string;

  // Execution tracking
  execution_started_at: string | null;
  execution_completed_at: string | null;
  execution_success: number | null; // 0 or 1
  execution_error: string | null;

  // Git tracking
  commit_sha: string | null;
  files_changed: string | null; // JSON array
  lines_added: number | null;
  lines_removed: number | null;

  // Revert tracking
  was_reverted: number; // 0 or 1
  revert_detected_at: string | null;
  revert_commit_sha: string | null;

  // User feedback
  user_satisfaction: number | null; // 1-5
  user_feedback: string | null;

  created_at: string;
  updated_at: string;
}

/**
 * Brain Reflection - tracks autonomous reflection sessions
 */
export interface DbBrainReflection {
  id: string;
  project_id: string;
  status: ReflectionStatus;
  trigger_type: ReflectionTriggerType;
  scope: ReflectionScope;

  // Analysis scope
  directions_analyzed: number;
  outcomes_analyzed: number;
  signals_analyzed: number;

  // Results
  guide_sections_updated: string | null; // JSON array
  error_message: string | null;

  // Timing
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
}

/**
 * Typed evidence reference — discriminated by entity type so resolution
 * can dispatch to the correct repository instead of guessing from IDs.
 */
export type EvidenceRefType = 'direction' | 'signal' | 'reflection';

export interface EvidenceRef {
  type: EvidenceRefType;
  id: string;
}

/**
 * Learning Insight - generated by reflection
 */
export interface LearningInsight {
  type: 'preference_learned' | 'pattern_detected' | 'warning' | 'recommendation';
  title: string;
  description: string;
  confidence: number; // 0-100
  evidence: EvidenceRef[];
  evolves?: string; // title of previous insight this one updates
  // Conflict detection fields
  conflict_with?: string; // title of conflicting insight
  conflict_type?: 'semantic' | 'keyword' | 'direct'; // how conflict was detected
  conflict_resolved?: boolean; // whether user has resolved the conflict
  conflict_resolution?: 'keep_both' | 'keep_this' | 'keep_other' | 'merge'; // resolution choice
  // Auto-pruning fields
  auto_pruned?: boolean; // whether this insight was auto-pruned (confidence lowered or conflict auto-resolved)
  auto_prune_reason?: string; // why it was auto-pruned
  original_confidence?: number; // confidence before auto-pruning
}

/**
 * Database row for brain_insights table (first-class insight entity)
 */
export interface DbBrainInsight {
  id: string;
  reflection_id: string;
  project_id: string;
  type: LearningInsight['type'];
  title: string;
  description: string;
  confidence: number;
  evidence: string; // JSON array of direction/signal IDs
  evolves_from_id: string | null; // FK to previous insight ID
  evolves_title: string | null; // original title for display (before FK was resolved)
  // Conflict fields
  conflict_with_id: string | null; // FK to conflicting insight
  conflict_with_title: string | null; // title for display
  conflict_type: string | null; // 'semantic' | 'keyword' | 'direct'
  conflict_resolved: number; // 0 or 1 (SQLite boolean)
  conflict_resolution: string | null; // 'keep_both' | 'keep_this' | 'keep_other' | 'merge'
  // Auto-pruning fields
  auto_pruned: number; // 0 or 1
  auto_prune_reason: string | null;
  original_confidence: number | null;
  // Timestamps
  created_at: string;
  updated_at: string;
}

/**
 * Aggregated behavioral context for prompt injection
 */
export interface BehavioralContext {
  hasData: boolean;

  // Current focus (what user is working on NOW)
  currentFocus: {
    activeContexts: Array<{ id: string; name: string; activityScore: number }>;
    recentFiles: string[];
    recentCommitThemes: string[];
  };

  // Trending areas (patterns over past week)
  trending: {
    hotEndpoints: Array<{ path: string; trend: 'up' | 'down' | 'stable'; changePercent: number }>;
    activeFeatures: string[];
    neglectedAreas: string[];
  };

  // Implementation patterns
  patterns: {
    successRate: number;
    recentSuccesses: number;
    recentFailures: number;
    revertedCount: number;
    averageTaskDuration: number;
    preferredContexts: string[];
  };

  // Top insights from Brain reflections (high-confidence, proven helpful)
  topInsights: Array<{
    title: string;
    type: LearningInsight['type'];
    description: string;
    confidence: number;
  }>;
}

/**
 * Reflection configuration
 */
export interface ReflectionConfig {
  enabled: boolean;
  triggerThreshold: number; // decisions before reflection
  minGapHours: number; // minimum hours between reflections
  maxDecisionsToAnalyze: number;
  autoUpdateGuide: boolean;
}

/**
 * Create input types
 */
export interface CreateBehavioralSignalInput {
  id: string;
  project_id: string;
  signal_type: BehavioralSignalType;
  context_id?: string | null;
  context_name?: string | null;
  data: string; // JSON
  weight?: number;
  timestamp: string;
}

export interface CreateDirectionOutcomeInput {
  id: string;
  direction_id: string;
  project_id: string;
  execution_started_at?: string;
}

export interface CreateBrainReflectionInput {
  id: string;
  project_id: string;
  trigger_type: ReflectionTriggerType;
  scope?: ReflectionScope;
}
