/**
 * Healing Issue Repository
 * Manages healing issues generated by the healing engine
 */

import { getConnection } from '../drivers';
import type { DbPersonaHealingIssue } from '../models/persona.types';

function generateId(): string {
  return 'phi_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

export const healingIssueRepository = {
  getAll(status?: string): DbPersonaHealingIssue[] {
    const db = getConnection();
    if (status) {
      return db.prepare(
        'SELECT * FROM persona_healing_issues WHERE status = ? ORDER BY created_at DESC'
      ).all(status) as unknown as DbPersonaHealingIssue[];
    }
    return db.prepare(
      'SELECT * FROM persona_healing_issues ORDER BY created_at DESC'
    ).all() as unknown as DbPersonaHealingIssue[];
  },

  getByPersona(personaId: string): DbPersonaHealingIssue[] {
    const db = getConnection();
    return db.prepare(
      'SELECT * FROM persona_healing_issues WHERE persona_id = ? ORDER BY created_at DESC'
    ).all(personaId) as unknown as DbPersonaHealingIssue[];
  },

  create(issue: Omit<DbPersonaHealingIssue, 'id' | 'created_at' | 'resolved_at' | 'auto_fixed' | 'status'>): DbPersonaHealingIssue {
    const db = getConnection();
    const id = generateId();
    db.prepare(
      `INSERT INTO persona_healing_issues (id, persona_id, execution_id, title, description, severity, category, suggested_fix)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(
      id,
      issue.persona_id,
      issue.execution_id || null,
      issue.title,
      issue.description,
      issue.severity,
      issue.category,
      issue.suggested_fix || null
    );
    return db.prepare('SELECT * FROM persona_healing_issues WHERE id = ?').get(id) as unknown as DbPersonaHealingIssue;
  },

  resolve(id: string): void {
    const db = getConnection();
    db.prepare(
      `UPDATE persona_healing_issues SET status = 'resolved', resolved_at = datetime('now') WHERE id = ?`
    ).run(id);
  },

  delete(id: string): void {
    const db = getConnection();
    db.prepare('DELETE FROM persona_healing_issues WHERE id = ?').run(id);
  },

  getOpenCount(): number {
    const db = getConnection();
    const result = db.prepare(
      `SELECT COUNT(*) as count FROM persona_healing_issues WHERE status = 'open'`
    ).get() as unknown as { count: number } | undefined;
    return result?.count || 0;
  },
};
